sudo: required

language: bash

services:
    - docker

before_install:
    - docker info
    - docker version

install:
    - docker build -t kevincoakley/centos7-ansible centos/7/
    - docker build -t kevincoakley/ubuntu15.10-ansible ubuntu/15.10/
    - docker build -t kevincoakley/ubuntu16.04-ansible ubuntu/16.04/

script:
    - bash ./tests/centos_7.sh
    - bash ./tests/ubuntu_1510.sh
    - bash ./tests/ubuntu_1604.sh

after_script:
    - docker ps -a
    - docker logs my_centos7-ansible
    - docker logs my_ubuntu15.10-ansible
    - docker logs my_ubuntu16.04-ansible
